#!/bin/sh

#################################################################
# Open a new tab in Gnome-Terminal
# 
# Author: Nils Hellerhoff <nils.hellerhoff@gmail.com>
# Date: 2020-12-11 
#
# Gnome-Terminal does not have a new-tab option. Therefore this script will
# check wheter gnome-terminal is running, focus the window and then execute
# Ctrl+Shift+t in the window, which will open a new tab
#
# Requirements:
# - wmtctrl
# - xdotool
################################################################

# get the id of the current desktop
currDesktopId=$(wmctrl -d | grep "*" | head -c 1)

# check whether there is a gnome-terminal open on the current desktop
otp=$(wmctrl -l -x | grep "$currDesktopId gnome-terminal-server.Gnome-terminal")

if [ -z "$otp" ]; then
    # we have no gnome-terminal open on the current desktop
    # create new window
    gnome-terminal
else
    # get the window id of gnome-terminal on the current desktop
    windowId=$(echo $otp | cut -d' ' -f1)

    # activate the window with the id $windowId
	wmctrl -x -a -i $windowId

    # wait shortly and open a new tab
	sleep 0.3
	xdotool key --clearmodifiers Ctrl+Shift+t
fi
