#!/bin/sh

#################################################################
# Open a new tab in Gnome-Terminal
# 
# Author: Nils Hellerhoff <nils.hellerhoff@gmail.com>
# Date: 2020-12-11 
#
# Gnome-Terminal does not have a new-tab option. Therefore this script will
# check wheter gnome-terminal is running, focus the window and then execute
# Ctrl+Shift+t in the window, which will open a new tab
#
# Requirements:
# - wmtctrl
# - xdotool
################################################################

otp=$(pgrep gnome-terminal)

if [ "$?" -eq 0 ]; then
	str="gnome-terminal-server.Gnome-terminal"
	wmctrl -x -a $str
	sleep 0.3
	xdotool key --clearmodifiers Ctrl+Shift+t
else
	gnome-terminal
fi
